### ISSUE TITLE
Phrases should be moved to ladjs/api

### ISSUE THREAD

**Issue by OmgImAlexis** [ladjs/lad#331]
Testing can't be finished on that repo until the phrases and other locals are sorted.

```
Error: Translation for your locale failed, try again
    at Object.ctx.translate (/Users/xo/code/@ladjs/api/node_modules/@ladjs/i18n/src/index.js:154:16)
    at Server.app.use (/Users/xo/code/@ladjs/api/index.js:27:183)
    at dispatch (/Users/xo/code/@ladjs/api/node_modules/koa/node_modules/koa-compose/index.js:42:32)
    at next (/Users/xo/code/@ladjs/api/node_modules/koa/node_modules/koa-compose/index.js:43:18)
    at /Users/xo/code/@ladjs/api/node_modules/koa-passport/lib/framework/koa.js:60:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Ref: https://github.com/ladjs/lad/blob/master/template/config/phrases.js

**Comment by OmgImAlexis** [comment]
@niftylettuce thoughts of adding the phrases as an export of `@ladjs/i18n`?
