### ISSUE TITLE
Fix tests so that they can run in parallel

### ISSUE THREAD

**Issue by niftylettuce** [ladjs/lad#334]
Right now the only way tests will pass is with `serial: true`.

If you run `ava` from within the `templates/` folder, you'll see the tests fail.

In the output, there is a debug statement with a stack trace thanks to <https://github.com/niftylettuce/max-listeners-exceeded-warning>.

However I have not been able to figure out what listener is binding 10+ times and causing this issue.  I think that the event listener should be unbound automatically after the tests end, but I'm not sure what listener is not being unbound.

**Comment by niftylettuce** [comment]
Of course before running `ava`, you'll need to remove from `template/package.json` the `ava` block for configuration.

**Comment by niftylettuce** [comment]
Here's the example debug statement and stack trace that I am referencing:

```sh
Error: Too many listeners of type "listening" added to EventEmitter. Max is 10 and we've added 12.
    at Server.addListener (/Users/test/Projects/lad/template/node_modules/max-listeners-exceeded-warning/index.js:10:19)
    at Server.once (events.js:341:8)
    at Server.listen (net.js:1431:10)
    at Server.listen (/Users/test/Projects/lad/template/node_modules/@ladjs/web/index.js:354:31)
    at Test.beforeEach [as fn] (/Users/test/Projects/lad/template/test/helpers/web.js:6:23)
    at Test.callFn (/Users/test/Projects/lad/template/node_modules/ava/lib/test.js:306:18)
    at Test.run (/Users/test/Projects/lad/template/node_modules/ava/lib/test.js:319:23)
    at runNext (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:58:44)
    at Sequence.run (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:90:10)
    at Concurrent.run (/Users/test/Projects/lad/template/node_modules/ava/lib/concurrent.js:41:37)
    at runNext (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:58:44)
    at Sequence.run (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:90:10)
    at runNext (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:58:44)
    at promise.then.passed (/Users/test/Projects/lad/template/node_modules/ava/lib/sequence.js:86:12)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
