### ISSUE TITLE
Require error after clean init

### ISSUE THREAD

**Issue by musla** [ladjs/lad#44]
After clean init of igloo (eskimo create ...) got this error: 

Error: req.flash() requires sessions
   at Error (<anonymous>)
   at IncomingMessage._flash [as flash](e:nodetigloonode_modulesconnect-flashlibflash.js:60:41)
   at Object.res.format.html (e:\node\tigloo\node_modules\igloo\lib\boot\error-handler.js:92:15)
   at ServerResponse.res.format (e:\node\tigloo\node_modules\express\lib\response.js:663:13)
   at e:\node\tigloo\node_modules\igloo\lib\boot\error-handler.js:84:11
   at Layer.handle_error (e:\node\tigloo\node_modules\express\lib\router\layer.js:52:5)
   at trim_prefix (e:\node\tigloo\node_modules\express\lib\router\index.js:261:13)
   at e:\node\tigloo\node_modules\express\lib\router\index.js:230:9
   at Function.proto.process_params (e:\node\tigloo\node_modules\express\lib\router\index.js:305:12)
   at e:\node\tigloo\node_modules\express\lib\router\index.js:221:12

**Comment by elkassar** [comment]
I got the same error. Although, Redis is connected.

info: app listening on 0.0.0.0:3000
info: app booted
info: redis connected
info: mongo connection opened

Any idea?
